# docker-compose.yml
version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      HOST: 0.0.0.0
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - .:/home/app/
      - ./node_modules:/home/app/node_modules

  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
